---
    - name: DOCKER PERMISSION
      shell: "sudo chmod -R 777 /var/run/docker.sock"

    - name: DOCKER KULLANICI IZNI
      shell: "sudo usermod -aG docker $USER"

#    - name: NEWGRP DOCKER
#      shell: "sudo newgrp docker"

    - name: HELLO WORLD
      shell: "sudo docker run hello-world"
      ignore_errors: true
